# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81289b3627a4fcf9087c7e859971e4ff"
name = "EU Withdrawal Button Made Easy"
application_url = "https://eu-withdrawal-button-web-production.up.railway.app"
embedded = true
handle = "eu-withdrawal-button-2026"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions-update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_online_store_pages"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://eu-withdrawal-button-web-production.up.railway.app/auth/callback"
]

[pos]
embedded = false
