[[extensions]]
name = "Support Extension"
handle = "support-link"
type = "admin_link"
uid = "b2d65ba8-7075-82c8-3905-e552772f66269bdc9d91"

[[extensions.targeting]]
target = "admin.app.support.link"
url = "app://help"